config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :users, only: %i[index]

  resources :categories, only: %i[index show new create destroy] do
    resources :transactions, only: %i[new create destroy]
  end

  resources :splash, only: %i[index]
  root 'splash#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user || User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Category, user_id: user.id
      can :manage, Transaction, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true, length: { in: 1..50 }
  validates :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :transactions
  validates :name, presence: true, length: { in: 1..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    @transactions = @category.transactions.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)

    if category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      redirect_to categories_path, alert: 'Failed to create new category'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy!
      flash[:notice] = 'Category deleted!'
      redirect_to categories_path
    else
      flash[:alert] = 'Failed to delete category!'
    end
  end

  private

  def category_params
    category = params.require(:category).permit(:name, :icon, :user_id)
    category[:user_id] = current_user.id
    category
  end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def respond_to_on_destroy
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name), status: :see_other }
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to users_path if user_signed_in?
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new
    @category = Category.where(author_id: current_user.id)
  end

  def create
    transaction = Transaction.new(transaction_params)

    if transaction.save
      redirect_to category_url(transaction.category), notice: 'Transaction was successfully created.'

    else
      redirect_to category_url(transaction.category), notice: 'Failed to create new transaction!'
    end
  end

  def destroy
    transaction = Transaction.find(params[:id])

    if transaction.destroy!
      redirect_to categories_url, notice: 'Transaction was successfully deleted.'
    else
      redirect_to categories_url, notice: 'Faile to delete transaction.'
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def transaction_params
    transaction = params.require(:transaction).permit(:name, :amount, :category_id)
    transaction[:user_id] = current_user.id
    transaction
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<%= link_to category do %>
<div id="<%= dom_id category %>" class="flex gap-4 flex-1">
  <img src="<%= category.icon %>" alt='Category icon' class="w-20 rounded-md" />
  <div>
      <h3 class='text-zinc-500 text-xl font-bold'>
        <%= category.name %>
      </h3>
      <h3 class='font-bold'>$
      <%=category.transactions.sum(:amount) %>
  </h3>
  </div>
</div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(:class => "flex flex-col gap-4", model: category) do |form| %>
  <div class='flex flex-col'>
    <%= form.label :name, class: 'text-base text-blue-400 font-bold' %>
    <%= form.text_field :name, class: 'p-1 border-2 border-blue-300 rounded-md' %>
  </div>

  <div class='flex flex-col'>
    <%= form.label :icon, class: 'text-base text-blue-400 font-bold' %>
    <%= form.text_field :icon, class: 'p-1 border-2 border-blue-300 rounded-md' %>
  </div>

  <div class='self-center'>
    <%= form.submit :Save, class: 'text-slate-50 font-bold border bg-blue-400 rounded-md py-1 px-5' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<section class='flex flex-col justify-between items-between h-full bg-zinc-200'>  
    <% if @categories.exists? %>
      <div class='flex flex-col gap-2'>
      <h1 class='text-2xl font-bold text-white self-center mb-2 bg-blue-800 w-full text-center p-3 pb-6'>Categories</h1>
        <% @categories.each do |category| %>
          <div class='flex justify-between items-center bg-slate-50 p-2 mx-2 rounded-md'>
            <%= render category %>
            <%= button_to "Delete", category_path(category), method: :delete, :class => "font-bold rounded-md p-1 bg-red-500 text-slate-50" %>
          </div>
        <% end %> 
      </div>
    <% else %> 
      <p></p>
       <%= image_tag "tranzkt_transparent.png", :class => "" %>
    <% end %> 
    <div class='w-full bg-lime-500 p-3 flex justify-center'>
      <%= link_to "Add Category", new_category_path, :class => "rounded-md border border-slate-50 text-xl text-white text-center bg-lime-500 w-3/4 p-1" %>
    </div>
</section>

app/views/categories/new.html.erb
<section class='flex flex-col justify-start gap-4 items-center h-full bg-blue-100'>
  <h1 class='text-white text-xl font-bold p-4 bg-blue-800 w-full text-center'>New Category</h1>
  <div>
    <%= render "form", category: @category %>
  </div>
</section>

app/views/categories/show.html.erb
<section class='flex flex-col justify-between items-between h-full bg-zinc-200'>
<div class='flex flex-col gap-5'>
<h3 class='text-2xl font-bold text-white self-center p-3 pb-6 bg-blue-800 w-full text-center'>Transactions</h3>
    <div class='flex items-center flex-col gap-2'>
      <h2 class='text-3xl font-bold text-blue-500'>
        <%= @category.name %>
      </h2>
      <div class='flex justify-between gap-4'>
      <p class='font-bold'> Total Amount: $
      <%=@category.transactions.sum(:amount) %>
      </p>
      <%= button_to "Delete", @category, method: :delete, :class => "font-bold rounded-md p-1 bg-red-500 text-slate-50" %>
    </div>
    </div>
    <% if @transactions.exists? %>
      <div class='flex flex-col gap-2'>
        <% @transactions.each do |transaction| %>
        <div class='bg-slate-50 p-2 mx-2 rounded-md'> 
            <%= render transaction %>
          </div>
        <% end %>
      </div>
    <% else %>  
       <%= image_tag "tranzkt_transparent.png" %>
    <% end %>
</div>
<div class='w-full bg-lime-500 p-3 flex justify-center'>
<%= link_to "Add Transaction", new_category_transaction_path(@category), :class => "rounded-md border border-slate-50 text-xl text-white text-center bg-lime-500 w-3/4 p-1" %>
</div>
</section>

app/views/layouts/_alerts.html.erb
<div class="absolute bottom-12 right-2 h-16 w-56">
<% if notice %>
  <p class="bg-lime-500 text-slate-50 font-bold p-2 rounded-md text-center"><%= notice %></p>
<% elsif alert %>
  <p class="bg-red-500 text-slate-50 font-bold p-2 rounded-md text-center"><%= alert %></p>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<section class='fixed top-4 flex justify-between  items-center w-full px-3'>
   <% if controller_name == 'categories' && action_name == 'index' %>
           <p></p>
           <%= link_to image_tag("sign-out.png",:class => "w-6 h-6" ), destroy_user_session_path, data: { "turbo-method":
        :delete } %>
        <% elsif controller_name == 'users' && action_name == 'index'%>
          <p></p>
           <%= link_to image_tag("sign-out.png",:class => "w-6 h-6" ), destroy_user_session_path, data: { "turbo-method":
           :delete } %>
         <% elsif controller_name == 'splash'%>  
            <p></p>
       <% elsif controller_name == 'sessions' || controller_name == 'registrations' %>  
            <%= link_to image_tag("back1.png",:class => "w-6 h-6" ), root_path %>
       <% else %>
        <%= link_to image_tag("back1.png",:class => "w-6 h-6" ), categories_path %>
      <%= link_to image_tag("sign-out.png",:class => "w-6 h-6" ), destroy_user_session_path, data: { "turbo-method":
        :delete } %>

   <% end %>        
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='h-screen m-0 p-0'>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<section class='flex flex-col justify-around items-between h-full bg-slate-50 pt-6'>
  <%= image_tag "tranzkt_transparent.png" %>
  <div class='w-full flex flex-col items-center gap-2'>
    <%= link_to "Log in", new_user_session_path, :class => "rounded-md border border-slate-50 text-xl text-white text-center bg-blue-700 p-2 w-4/5" %>
    <%= link_to "Sign up", new_user_registration_path, :class => "rounded-md border border-slate-50 text-xl text-white text-center bg-blue-700 p-2 w-4/5" %>
  </div>
</section>

app/views/transactions/_form.html.erb
<%= form_with(:class => "flex flex-col gap-4",model: transaction, url: category_transactions_path(@category)) do |form| %>
  <div class='flex flex-col'>
    <%= form.label :category_id, class: 'text-base text-blue-400 font-bold' %>
    <%= form.collection_select :category_id, current_user.categories, :id, :name, prompt: true, class: 'bg-slate-50' %>
  </div>

  <div class='flex flex-col'>
    <%= form.label :name, class: 'text-base text-blue-400 font-bold' %>
    <%= form.text_field :name, class: 'p-1 border-2 border-blue-300 rounded-md' %>
  </div class='flex flex-col'>

  <div class='flex flex-col'>
    <%= form.label :amount, class: 'text-base text-blue-400 font-bold' %>
    <%= form.number_field :amount, class: 'p-1 border-2 border-blue-300 rounded-md' %>
  </div>

  <div class='self-center'>
    <%= form.submit :Save, class: 'text-slate-50 font-bold border bg-blue-400 rounded-md py-1 px-5' %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="flex flex-1 justify-between px-3">
  
  <p class='text-base font-bold text-blue-400'>
    <%= transaction.name %>
  </p>

  <p class='font-bold'>
    $
    <%= transaction.amount %>
  </p>
</div>

app/views/transactions/new.html.erb
<section class='flex flex-col justify-start gap-4 items-center h-full bg-blue-100'>

<h1 class='text-white text-xl font-bold p-4 bg-blue-800 w-full text-center'>New transaction</h1>

<%= render "form", transaction: @transaction %>

</section>

app/views/users/index.html.erb
<section class='flex flex-col justify-between items-between h-full bg-slate-100 pt-6'>
<p class='font-bold text-green-600 text-2xl self-center mt-8'>Welcome, <%= @user.name %></p>
  <%= image_tag "tranzkt_transparent.png"%>
  <div class='w-full bg-lime-500 p-3 flex justify-center'>
  <%= link_to "Start", categories_path, :class => "rounded-md border border-slate-50 text-xl text-white text-center bg-lime-500 w-3/4 p-1" %>
  </div>
</section>